### PR TITLE
Add upper constraint on `ipywidgets`

### PR DESCRIPTION
**Pull request by mattwthompson**
ref https://github.com/nglviewer/nglview/issues/1032

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
The "tests" are failing. I'm going to go out on a limb and say the log is not so useful here:

```
2022-08-18T21:39:51.1334634Z import: 'nglview'
2022-08-18T21:39:51.7516224Z import: 'nglview'
2022-08-18T21:39:51.8545630Z + jupyter labextension list
2022-08-18T21:39:51.8547708Z + grep -ie 'nglview-js-widgets.*OK'
2022-08-18T21:39:54.2855812Z Tests failed for nglview-3.0.3-pyhd355979_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
2022-08-18T21:39:54.2858376Z WARNING:conda_build.build:Tests failed for nglview-3.0.3-pyhd355979_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
2022-08-18T21:39:54.3314118Z TESTS FAILED: nglview-3.0.3-pyhd355979_1.tar.bz2
2022-08-18T21:40:01.2802742Z ##[error]Bash exited with code '1'.
2022-08-18T21:40:01.2840502Z ##[section]Finishing: Run docker build

**Comment by hainm** [comment]
@conda-forge-admin, please rerender

**Comment by szcc** [comment]
cool. I'll give a try!

**Comment by hainm** [comment]
image

**Pull request closed without merging**
