### PR TITLE
Update recipe for 2.7.7

### PR DESCRIPTION
**Pull request by ericpre**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

For next release, the recipe can be simplify, since enabling extension has changed in https://github.com/arose/nglview/pull/898. I used this branch to check the enabling mechanism, as  mentioned in
https://github.com/arose/nglview/issues/896#issuecomment-623998063.

### CODE REVIEW

**Comment by hainm** [comment]
hi @ericdill, can you please mere this PR (https://github.com/conda-forge/nglview-feedstock/pull/49) to your branch?

**Comment by ericpre** [comment]
Done and tested on linux and windows.

> hi @ericdill, can you please mere this PR (#49) to your branch?

I guess, you meant me and not @ericdill! ;)

**Comment by hainm** [comment]
@ericpre oops, I am sorry. Yeah, I meant you.

**Comment by hainm** [comment]
Please give it a try once the package is available. Thanks again.

**Comment by ericpre** [comment]
I have check on the 3 main platforms (windows, linux and macos) and the instructions at https://github.com/arose/nglview/tree/d41dfb92d1f6d40eac40da5ea5d6d4506101015f#released-version works fine (no need to run `jupyter-nbextension enable nglview --py --sys-prefix`).

**Pull request merged**
