### PR TITLE
depend ipywidgets<6. Fixes #1

### LINKED ISSUE #1: Can't sync orientation of view object
The current version if broken if installed via conda-forge. I can't access the orientation of a view object. To reproduce use the following to create a new view

```python
import nglview as ng
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF, DCD

u = mda.Universe(PSF, DCD)
view = ng.show_mdanalysis(u)
view._set_sync_camera()
```

now rotate the protein. `view.orientation` should now return a 3x3 matrix with the orientation. This might be due to using the new ipywidgets. The official package on bioconda still uses ipywidgets 5.x

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by kain88-de** [comment]
Can you also update the minor version while you are at it. Thanks.

**Comment by marscher** [comment]
@kain88-de The minimum version is already pinned

**Comment by kain88-de** [comment]
I meant that there is a newer version of nglview available.

**Comment by marscher** [comment]
sorry @kain88-de, that was merged too quickly. BTW do you have an interest of having merge rights here?

**Comment by marscher** [comment]
https://github.com/arose/nglview/compare/v0.6.2.3...v0.6.2.4 mhm, I dont think it is worth building another package for this version, as there are no differences.

**Comment by hainm** [comment]
that's my trick to build `nglview` in bioconda.

Your build on `conda-forge` lock my build on bioconda. The only way I can do is to increase version number.

https://github.com/bioconda/bioconda-recipes/issues/4038#issuecomment-287499291

**Comment by marscher** [comment]
Wow man, that's a strict policy. Sorry for the headache! Is there a workaround, eg. disabling linting for nglview?

**Comment by hainm** [comment]
I have not checked that yet. Here is the suggestion: https://github.com/bioconda/bioconda-recipes/issues/4038#issuecomment-287543630

**Comment by marscher** [comment]
I have no experience with "deprecating" a feedstock, which I guess is your preferred solution. Until we've found a working solution, I can promise not to update any more to avoid further trouble.

**Pull request merged**
